apiVersion: v1
kind: Secret
metadata:
  name: public-repo-karmada
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/paulofponciano/karmada.git
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: karmada
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Karmada binding
  sourceRepos:
    - 'https://github.com/paulofponciano/karmada.git'
  destinations:
    - namespace: '*'
      server: 'https://karmada-apiserver.karmada-system.svc.cluster.local:5443'
      name: 'in-cluster'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: karmada
  source:
    repoURL: https://github.com/paulofponciano/karmada.git
    targetRevision: HEAD
    path: manifests/redis
  destination:
    server: https://karmada-apiserver.karmada-system.svc.cluster.local:5443
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true