# propagationpolicy.yaml
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: demo-ms-canary-rollout-propagation
  namespace: default
spec:
  conflictResolution: Overwrite
  propagateDeps: true
  resourceSelectors:
    - apiVersion: argoproj.io/v1alpha1
      kind: Rollout
      name: demo-ms-canary
  placement:
    clusterAffinity:
      clusterNames:
        - pegasus-2
        - pegasus-3
    spreadConstraints:
      - maxGroups: 1
        minGroups: 1
    replicaScheduling:
      replicaSchedulingType: Duplicated
  failover:
    application:
      decisionConditions:
        tolerationSeconds: 60
      purgeMode: Graciously
      gracePeriodSeconds: 60
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: demo-ms-canary-services-propagation
  namespace: default
spec:
  conflictResolution: Overwrite
  propagateDeps: true
  resourceSelectors:
    - apiVersion: v1
      kind: Service
      name: demo-ms-stable
    - apiVersion: v1
      kind: Service
      name: demo-ms-canary
  placement:
    clusterAffinity:
      clusterNames:
        - pegasus-2
        - pegasus-3
    spreadConstraints:
      - maxGroups: 1
        minGroups: 1
  failover:
    application:
      decisionConditions:
        tolerationSeconds: 60
      purgeMode: Graciously
      gracePeriodSeconds: 60
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: demo-ms-canary-istio-propagation
  namespace: default
spec:
  conflictResolution: Overwrite
  propagateDeps: false
  resourceSelectors:
    - apiVersion: networking.istio.io/v1
      kind: VirtualService
      name: demo-ms-canary
    - apiVersion: networking.istio.io/v1
      kind: DestinationRule
      name: demo-ms-canary
    - apiVersion: networking.istio.io/v1
      kind: Gateway
      name: demo-ms-canary-gateway
  placement:
    clusterAffinity:
      clusterNames:
        - pegasus-2
        - pegasus-3
    spreadConstraints:
      - maxGroups: 1
        minGroups: 1
  failover:
    application:
      decisionConditions:
        tolerationSeconds: 60
      purgeMode: Graciously
      gracePeriodSeconds: 60
