apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: demo-ms-canary-rollout-propagation
  namespace: default
spec:
  resourceSelectors:
    - apiVersion: argoproj.io/v1alpha1
      kind: Rollout
      name: demo-ms-canary
  placement:
    clusterAffinity:
      clusterNames:
        - pegasus-2
        - pegasus-3
    replicaScheduling:
      replicaDivisionPreference: Weighted
      replicaSchedulingType: Divided
      weightPreference:
        staticWeightList:
          - targetCluster:
              clusterNames:
                - pegasus-2
            weight: 1
          - targetCluster:
              clusterNames:
                - pegasus-3
            weight: 1
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: demo-ms-canary-services-propagation
  namespace: default
spec:
  resourceSelectors:
    - apiVersion: v1
      kind: Service
      name: demo-ms-canary
    - apiVersion: v1
      kind: Service
      name: demo-ms-canary-canary
  placement:
    clusterAffinity:
      clusterNames:
        - pegasus-2
        - pegasus-3
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: demo-ms-canary-virtualservice-propagation
  namespace: default
spec:
  resourceSelectors:
    - apiVersion: networking.istio.io/v1
      kind: VirtualService
      name: demo-ms-canary
  placement:
    clusterAffinity:
      clusterNames:
        - pegasus-2
        - pegasus-3
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: demo-ms-canary-gateway-propagation
  namespace: default
spec:
  resourceSelectors:
    - apiVersion: networking.istio.io/v1
      kind: Gateway
      name: demo-ms-canary-gateway
  placement:
    clusterAffinity:
      clusterNames:
        - pegasus-2
        - pegasus-3
