apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-canary-pegasus2-view
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/paulofponciano/karmada.git
    path: app-manifests/app-canary
    targetRevision: HEAD
    directory:
      recurse: false
      exclude: '{*override*.yaml,*propagation*.yaml}'
  destination:
    name: pegasus-2
    namespace: default
  syncPolicy:
    syncOptions:
      - Validate=false
      - CreateNamespace=false
  ignoreDifferences:
    - group: argoproj.io
      kind: Rollout
      jsonPointers:
        - /spec/replicas
        - /status
        - /metadata/annotations
        - /metadata/resourceVersion
        - /metadata/uid
        - /metadata/generation
    - group: ""
      kind: Service
      jsonPointers:
        - /spec/selector/rollouts-pod-template-hash
        - /spec/clusterIP
        - /spec/clusterIPs
        - /metadata/annotations
        - /metadata/resourceVersion
        - /metadata/uid
