apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-canary
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/paulofponciano/karmada.git
    path: app-manifests/app-canary
    targetRevision: HEAD
  destination:
    name: karmada-controlplane
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
